---
- name: Install Java OpenJDK and Apache Maven
  package:
    name:
      - java-1.8.0-openjdk
      - maven
    state: latest

- name: Download and Extract Maven into /temp
  unarchive:
    src: "{{ maven_download_url }}"
    dest: "{{ download_folder }}"
    remote_src: yes

- name: Create symbolic link for Maven
  file:
    src: "{{ maven_path }}"
    dest: "/opt/maven"
    state: link

- name: Configure Maven and its environment variables
  lineinfile:
      dest: "{{maven_env_file}}"
      line: "{{ item.line }}"
      create: yes
      state: present
  with_items: 
    - { line: 'JAVA_HOME=/usr/lib/jvm/java-1.8.0-amazon-corretto.x86_64/jre' }
    - { line: 'M2_HOME=/opt/maven' }
    - { line: 'MAVEN_HOME=/opt/maven' }
    - { line: 'PATH=$PATH:$M2_HOME/bin' }
   
- name: Exports/Run maven env file for make M2_HOME available globally
  shell: "source {{maven_env_file}}"

- name: Download jenkins repo
  get_url:
    url: "{{ jenkins_download_url }}"
    dest: "{{ jenkins_repo_path }}"

- name: Import Jenkins CI key 
  rpm_key:
    key: "{{jenkins_key_url}}"
    state: present
 
- name: Install Jenkins
  package:
    name: jenkins
    state: latest
 
- name: Start the server
  service:
    name: jenkins
    state: started
- wait_for: 
    port: 8080
...