---
- name: Database server install
  hosts: ci
  become: true

  tasks:
   - name: Add official MariaDB repository
     yum_repository:
       name: MariaDB
       description: Official MariaDB repository
       baseurl: "http://yum.mariadb.org/10.4.3/centos7-amd64/"
       gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
       gpgcheck: true
     tags: mariadb

   - name: install MariaDB packages
     yum: pkg={{ item.name }} state=present
     with_items:
       - name: MariaDB
       - name: MariaDB-server
       - name: MySQL-python
     tags: mariadb

   - name: Start service mariadb, if not started
     service:
      name: mariadb       
      state: started
      enabled: yes
      
         - name: insert line in file
     lineinfile:
       path: /etc/my.cnf.d/server.cnf
       insertafter: '\[mysqld\]'
       line: "{{ item }}"
     loop:
       - character_set_server = 'utf8mb4'
       - innodb_file_per_table = 'ON'
       - innodb_file_format = Barracuda
       - innodb_file_per_table = 1
       - collation-server = utf8mb4_unicode_ci
       - skip-character-set-client-handshake
     notify:
       - restart mariadb

   - name: Check if root password is set
     shell: >
       mysqladmin -u root status
     changed_when: false
     failed_when: false
     register: root_pwd_check
     tags: mariadb

   - name: Set MariaDB root password for the first time (root@localhost)
     mysql_user:
       name: root
       password: "{{ mariadb_root_password }}"
       host: localhost
       state: present
     when: root_pwd_check.rc == 0
     tags: mariadb

   - name: Set MariaDB root password for 127.0.0.1, ::1
     mysql_user:
       name: root
       password: "{{ mariadb_root_password }}"
       host: "{{ item }}"
       login_user: root
       login_password: "{{ mariadb_root_password }}"
       state: present
     with_items:
       - ::1
       - 127.0.0.1
     when: root_pwd_check.rc == 0
     tags: mariadb

   - name: Remove the test database
     mysql_db:
       name: test
       login_user: root
       login_password: "{{ mariadb_root_password }}"
       state: absent
     tags: mariadb

   - name: Create user defined databases
     mysql_db:
       name: "{{ MAINDB }}"
       login_user: root
       login_password: "{{ mariadb_root_password }}"
       state: present
     register: db_creation
     tags: mariadb

   - name: Remove anonymous users
     mysql_user:
       name: ''
       host_all: true
       login_user: root
       login_password: "{{ mariadb_root_password }}"
       state: absent
     tags: mariadb

   - name: Create the users
     mysql_user:
       name: "{{ USERDB }}"
       password: "{{ PASSWDDB }}"
       host: 'localhost'
       priv: '*.*:ALL,GRANT'
       append_privs: 'yes'
       login_user: root
       login_password: "{{ mariadb_root_password }}"
       state: present
     tags: mariadb
